### ISSUE TITLE
verification failure when a byte is removed from a file

### ISSUE THREAD

**Issue by jcfp** [Parchive/par2cmdline#50]
hi,

a bug was reported in debian about a verification failure when bytes are missing from a file. Affected versions include 0.6.11 and 0.6.12, but not 0.4.

To reproduce:
* generate a random file: dd if=/dev/urandom of=random20M bs=20M count=1
* create a par set with default settings: par2 c random20M
* move the intact file out of the way: mv random20M random20M-intact
* remove a byte from the start of the file: tail -c 20971519 random20M-intact > random20M
* try verifying or reparing: par2 v random20M

Verification fails with the following output:
"""
$ par2 v random20M
Loading "random20M.par2".
Loaded 4 new packets
Loading "random20M.vol000+01.par2".
Loaded 1 new packets including 1 recovery blocks
Loading "random20M.vol003+04.par2".
Loaded 4 new packets including 4 recovery blocks
Loading "random20M.vol001+02.par2".
Loaded 2 new packets including 2 recovery blocks
Loading "random20M.vol031+32.par2".
Loaded 32 new packets including 32 recovery blocks
Loading "random20M.vol063+37.par2".
Loaded 37 new packets including 37 recovery blocks
Loading "random20M.vol015+16.par2".
Loaded 16 new packets including 16 recovery blocks
Loading "random20M.vol007+08.par2".
Loaded 8 new packets including 8 recovery blocks
Loading "random20M.par2".
No new packets found

There are 1 recoverable files and 0 other files.
The block size used was 10488 bytes.
There are a total of 2000 data blocks.
The total size of the data files is 20971520 bytes.

Verifying source files:

File: "random20M" - no data found.

Scanning extra files:

Repair is required.
1 file(s) exist but are damaged.
You have 0 out of 2000 data blocks available.
You have 100 recovery blocks available.
Repair is not possible.
You need 1900 more recovery blocks to be able to repair.
"""

With the same data, version 0.4 finds 1999 out of 2000 data blocks, as expected.

In case a byte is instead removed from somewhere in the middle of the random file, par2verify 0.6.11/12 will only find the data blocks upto the point of damage (and verification still fails, obviously).

Somehow test14, designed to test for exactly the "byte missing from the start"-scenario, manages to pass its testcase, albeit in a weird way. With its test-1.data repair is possible after removal of the first byte, but that takes 13 recovery blocks rather than just a single one. Removing some more bytes from the start of test-1.data (e.g. crop to 177000 bytes) decreases (!) the amount of recovery blocks needed to 2. Replacing test-1.data from test14 with a random file of the same size results in 0 data blocks found and test failure same as with random20M, so apparently the content of the file is somehow relevant (test-1.data is rather repetitive).

The debian bug report is at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785127

**Comment by PeterBClements** [comment]
This bug is a result of the fix that was implemented for bug #31.

In that case the issue was caused by what happens if the data slice currently being checked has a crc32 value that matches a slice in one of the sourcefiles, but where either the md5 hash does not match, or it does match, but the match is for a slice that has already been found (duplicate).

Before the fix for bug #31 was applied, the code would have stepped forward 1 byte in the file, and then checked the slice at the new offset to see if it is a match. The consequence of this is that if the file contains a lot of data where the crc32 would match but were the md5 would not (or where it might be reported as a duplicate), then the scanner could potentially computed the md5 hash at every possible offset within the file being scanned.

The fix that was applied attempted to ensure that whilst scanning through the file looking for matching slices, if it scanned more than a certain distance without finding a match, it would jump forwards in the file to where it thought it would be more likely to find a match.

Unfortunately, the distance that the fix jumps forward is such that it offset within the file at which it would start searching was always and exact multiple of the block size. This meant that and valid blocks with the file would never be found it they were positioned at an offset that was anywhere between 10 bytes after the expected offset and the expected offset for the following block.

i.e. any block that was slightly earlier in the file that it was supposed to be would never be found.

As for test14, that was not a valid test of the consequences of a single byte being removed from the beginning of a file.

I will release a fix for this shortly.

**Comment by PeterBClements** [comment]
Now fixed by latest patch.

**Comment by BlackIkeEagle** [comment]
@PeterBClements thanks, I'll tag and release later today

**Comment by jcfp** [comment]
Thanks, both of you. Great to see the legend is back at it :)

**Comment by 9Yg1rxeSeha90ZU1** [comment]
I tested the Ubuntu version 0.6.14 of par2 and see that although this patch is likely applied, the bug still exists. Additionally, even the latest MASTER branch is affected in a similar, but not identical way. As an example, I was able to corrupt numerous .par2 index files in ways that both v0.6.14 and MASTER par2 think 0 blocks are available. However, by replacing the .par2 file with an uncorrupted version, v0.6.14 par2 will think the repair is impossible due to corruption in the vol* blocks. However, MASTER par2 does allow repair. So, something is very funky and I think the fact that this is 2+ years ongoing means that the implementation is not dependable for numerous corruptions. Do you have additional and more robust test suites to validate such findings? What say you? Thanks for your efforts.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Just a note that the bugs I am seeing are being tested with a single vol* file -n1 option. Perhaps this is why? Does par2 fail in odd ways like this known to developers when using a single par2 vol*?

**Comment by BlackIkeEagle** [comment]
@9Yg1rxeSeha90ZU1 If you could create a script to indicate the bug it would be handy
